runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /js
  static_dir: public/static/js

- url: /css
  static_dir: public/static/css

- url: /.*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: ssl
  version: latest
